-- 코드를 작성해주세요
SELECT O.ID
FROM ECOLI_DATA O
JOIN (SELECT A.ID, A.PARENT_ID
      FROM ECOLI_DATA A
      JOIN (SELECT ID,PARENT_ID
            FROM ECOLI_DATA) B
      ON A.PARENT_ID = B.ID) T
ON O.PARENT_ID = T.ID

EXCEPT

SELECT O.ID
FROM ECOLI_DATA O
JOIN (SELECT A.ID, A.PARENT_ID
      FROM ECOLI_DATA A
      JOIN (SELECT C.ID, C.PARENT_ID
            FROM ECOLI_DATA C
            JOIN (SELECT ID, PARENT_ID
                  FROM ECOLI_DATA) D
            ON C.PARENT_ID = D.ID) B
      ON A.PARENT_ID = B.ID) T
ON O.PARENT_ID = T.ID
ORDER BY ID