-- 코드를 입력하세요
SELECT H.HISTORY_ID, TRUNCATE(((DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE) * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_TYPE = '트럭') C
ON H.CAR_ID = C.CAR_ID

LEFT JOIN (SELECT CAR_TYPE, DISCOUNT_RATE, REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') AS DURATION_TYPE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN) P
ON C.CAR_TYPE = P.CAR_TYPE
AND ((DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 90 AND DURATION_TYPE = 90
    OR (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 30 AND (DATEDIFF(H.END_DATE, H.START_DATE) + 1) < 90 AND DURATION_TYPE = 30
    OR (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 7 AND (DATEDIFF(H.END_DATE, H.START_DATE) + 1) < 30 AND DURATION_TYPE = 7)

ORDER BY FEE DESC, H.HISTORY_ID DESC