-- 코드를 입력하세요
SELECT M.MEMBER_NAME, G.REVIEW_TEXT, G.REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN (SELECT MEMBER_ID, COUNT(*) AS groupCount
      FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY groupCount DESC
      LIMIT 1) R
ON M.MEMBER_ID = R.MEMBER_ID
LEFT JOIN (SELECT MEMBER_ID, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
           FROM REST_REVIEW) G
ON R.MEMBER_ID = G.MEMBER_ID
ORDER BY G.REVIEW_DATE, G.REVIEW_TEXT