SELECT C.ITEM_ID,
       C.ITEM_NAME,
       C.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO P  -- 부모 아이템
  ON T.PARENT_ITEM_ID = P.ITEM_ID
JOIN ITEM_INFO C  -- 자식 아이템
  ON T.ITEM_ID = C.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC;