-- 코드를 작성해주세요
WITH MAX_SIZE_BY_YEAR AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
           MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT 
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    (MS.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV,
    ED.ID
FROM ECOLI_DATA ED
JOIN MAX_SIZE_BY_YEAR MS
  ON YEAR(ED.DIFFERENTIATION_DATE) = MS.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;