-- 코드를 작성해주세요
SELECT J.ID, N.FISH_NAME, J.LENGTH
FROM FISH_INFO J
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE) I
    ON J.FISH_TYPE = I.FISH_TYPE
    AND J.LENGTH = I.LENGTH
JOIN FISH_NAME_INFO N
    ON N.FISH_TYPE = J.FISH_TYPE
ORDER BY J.ID
